name: main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/master'}}
    runs-on: windows-2022
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      myrepo_url: "https://github.com/MehdiChinoune/MSYS2-packages/releases/download/msys-x86_64-v3"

    steps:
      - uses: actions/checkout@v3
        with:
          path: temp
          fetch-depth: 0

      # to match the autobuild environment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: VCS base-devel pactoys
          update: true

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[staging]\nServer = https://repo.msys2.org/staging/\nSigLevel = Never\n|' /etc/pacman.conf

      - name: Add myrepo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[msys-x86_64-v3]\nServer = ${{ env.myrepo_url }}/\nSigLevel = Never\n|' /etc/pacman.conf
          cat /etc/pacman.conf

      - name: Update using staging/myrepo
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CI-Build
        shell: msys2 {0}
        run: |
          cd /C/_
          ./.ci/ci-build.sh

      - name: "Upload binaries"
        uses: actions/upload-artifact@v3
        with:
          name: msys2-packages
          path: C:/_/artifacts/*.pkg.tar.*

      - name: "Upload sources"
        uses: actions/upload-artifact@v3
        with:
          name: sources
          path: C:/_/artifacts/*.src.tar.*

      - name: Download myrepo database files
        run: |
          cd temp
          gh release download msys-x86_64-v3 -p 'msys-x86_64-v3*' -D myrepo

      - name: Update local database files
        shell: msys2 {0}
        run: |
          repo-add temp/myrepo/msys-x86_64-v3.db.tar.gz /c/_/artifacts/*.pkg.tar.*
          rm temp/myrepo/*.old

      - name: Upload packages and database
        shell: bash
        run: |
          cd temp
          gh release upload msys-x86_64-v3 C:/_/artifacts/*.pkg.tar.* myrepo/* --clobber

  package-grokker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4.1.7
        id: artifacts
        continue-on-error: true
        with:
          name: msys2-packages
          path: artifacts
      - name: Grok packages
        uses: jeremyd2019/package-grokker/grok-artifacts@main
        if: steps.artifacts.outcome == 'success'
        with:
          repo: msys
          path: artifacts
